# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 'PlayNine CI (Build and Publish)'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm ci
    - run: npm run build
    - run: npm run test
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        # Artifact name
        name: ${{ matrix.node-version }}
        path: 'build'
        retention-days: 10
  
  publish:
    name: 'Publish site to surge'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.9
      with:
        name: '15.x'
        path: './build'

    - name: Publish to surge.sh
      uses: dswistowski/surge-sh-action@v1.0.1
      with:
        domain: 'play-nine-demo.surge.sh'
        project: 'build'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}
